---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-access-admin
  namespace: cluster-access
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-access-admin-token
  namespace: cluster-access
  annotations:
    kubernetes.io/service-account.name: cluster-access-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-access-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-access-admin-binding
subjects:
- kind: ServiceAccount
  name: cluster-access-admin
  namespace: cluster-access
roleRef:
  kind: ClusterRole
  name: cluster-access-admin
  apiGroup: rbac.authorization.k8s.io 