apiVersion: v1
kind: Namespace
metadata:
  name: cluster-access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-access-readonly
  namespace: cluster-access
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-access-readonly-token
  namespace: cluster-access
  annotations:
    kubernetes.io/service-account.name: cluster-access-readonly
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-access-readonly
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-access-readonly-binding
subjects:
- kind: ServiceAccount
  name: cluster-access-readonly
  namespace: cluster-access
roleRef:
  kind: ClusterRole
  name: cluster-access-readonly
  apiGroup: rbac.authorization.k8s.io 