apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: {{ .Values.runnerScaleSetVersion }}
    helm:
      values: |-
        githubConfigUrl: {{ .Values.githubConfigUrl }}
        githubConfigSecret: {{ .Values.githubConfigSecret }}
        controllerServiceAccount:
          name: arc-systems-gha-rs-controller
          namespace: arc-systems
  destination:
    server: {{ .Values.destinationServer }}
    namespace: arc-runners
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
