---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster-connector
spec:
  hostname: cluster-connector
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "10.96.0.0/16"
